### ISSUE TITLE
Resurrecting ValueDispatch

### ISSUE THREAD

**Issue by gdziadkiewicz** [zachallaun/ValueDispatch.jl#3]
@zachallaun 
Would you accept an PR which would make ValueDispatch functional under Julia 0.4?

**Comment by zachallaun** [comment]
Hi Grzegorz,

I'm not in a position to do a good job of maintaining this project. I'm
happy to give you or anyone else my blessing to fork this and submit the
fork as the official version of the package; please let me know what, if
anything, is needed to make that transition smooth.

Thanks,
Zach

**Comment by gdziadkiewicz** [comment]
I believe that due to Julia package system the smoothest transition would be either transferring the repo ownership or adding as collaborator. Is any of those options acceptable for you?
